### ISSUE TITLE
[post-1.50] Split installation of non-essential modules / SRFIs

### ISSUE THREAD

**Issue by jpellegrini** [egallesio/STklos#104] opened 2020-08-17 14:11 UTC
It would be nice if it was possible to do things like these:

```
make install-core
make install-modules srfi-13 srfi-151
make uninstall-modules srfi-35
```

so one could have a very small installation of STklos without effort.

This shouldn't be too hard to implement.

**Comment by egallesio** [comment] 2020-08-17 16:17
Hi @jpellegrini 

Reducing the siez of what is installed is a good idea. The problem is that we could have people with different libs or (worse) old versions of files of an old complete installation which lye down in the install directory. What do you think of having an installation without the manual and without the *.stk files. It has the advantage that the really useful files would be always present on all installations. Some numbers:

On the (released) 1.50: 
   - actual installation: 6.3Mb
  - without the doc directory and without the .stk files: 2.4Mb

Do you think that 2.4 Mb is acceptable for an installation on a machine such as a router?

**Comment by jpellegrini** [comment] 2020-08-17 17:40
> The problem is that we could have people with different libs or (worse) old versions of files of an old complete installation which lye down in the install directory

Ah, I had not thought about that, you're right.

When compiling for OpenWRT, there is a staging installation, and then I pick the files for the package. So I already leave the docs out. It would be nice to have a separate doc install target, it would make it easier.

I was thinking that it could be possible to have installations with specific sets of modules, but as you mentioned, it may not be a good idea.

**Comment by egallesio** [comment] 2020-08-19 16:56
Do you think that the file `DOCDB` should be part of the base installation? 

```
-rw-r--r-- 1 eg eg 302973 Aug 19 18:42 doc/DOCDB
```
It is one of the bigger file of the system, so a good candidate for not being present. On the other side, having it permits to use the 
`help` function (and I  think that we have a fully functional installation with less than 2.5Mb.

**Comment by jpellegrini** [comment] 2020-08-19 18:05
I think the DOCDB is important, although it could be part of a "`make install-doc`" target. Do you agree?

**Comment by jpellegrini** [comment] 2020-08-28 18:35
I see the new commit that splits installation into essential, sources, doc -- that is GREAT!

**Comment by egallesio** [comment] 2020-08-29 16:30
That is true that the difference is quite important. That was a great idea. Thanks for suggesting.

**Comment by jpellegrini** [comment] 2020-08-30 22:49
For OpenWRT, I was trying to remove the sources and documentation with a script... DOCDB wasn't removed. 

The previous OpenWRT package had 2.3Mb size. The new one, with only `install-base`, is **415k**!!!

I suppose we can close this now?

**Comment by jpellegrini** [comment] 2020-08-31 10:15
Just one thing: is `/usr/share/stklos/1.50/Demos.d/`necessary in `install-base`?
And what about `/usr/share/stklos/1.50/silex.scm` -- it seems pretty large.

**Comment by egallesio** [comment] 2020-09-01 07:47
> Just one thing: is /usr/share/stklos/1.50/Demos.d/necessary in install-base?

No you are right 

> And what about /usr/share/stklos/1.50/silex.scm -- it seems pretty large.- strip the stklos executable
:+1: 

Here are the changes of last commit:
- tag the executable with the version to allow intallation of several
  versions of STklos. This point needs some more work to be completely
  clean (include files should be in the shared directory, and scripts
  too, but it works at least for the interactive interpreter)
- don't install the source of SIlex which is not necessary since
  `stklos-genlex` embeds a compiled version of it. 
- don't install the demos (which are no more installed btw).

It should reduce again the size of the installation. Tell me please if it is OK for you.

**Comment by jpellegrini** [comment] 2020-09-01 13:58
Hi @egallesio - i'm away from the computer for a few days. Will check that when i'm back

**Comment by egallesio** [comment] 2020-09-01 14:37
Hope that everything is OK for you and that you are just taking some rest. Enjoy it,  you deserve it.

**Comment by jpellegrini** [comment] 2020-09-04 00:21
Hi.
I'm back and will be able to work for a few days. Yes, it's much better!

I thought it would be a good idea to srtip the STklos binary, but I see now that calling "strip" in the Makefile seems to not work when cross-compiling (the host "strip" is called, and doesn't recognize the binary format). So I manually strip after installing into a stage dir.

Anyway, the OpenWRT binary package (compressed) is now 376k only! That's great!

**Comment by jpellegrini** [comment] 2020-09-04 11:05
Also... I believe `scmpkg-support.stk` and `help.ostk` could be removed also (help won't work anyway).

**Comment by egallesio** [comment] 2020-09-07 14:21
> I'm back and will be able to work for a few days. Yes, it's much better!

Glad to see you back and happy that you are healthy. 
Here, courses are beginning and I will be a little bit slow for a moment.

**Comment by egallesio** [comment] 2020-09-07 16:00
I have added a new target `install-base-no-strip` to avoid stklos stripping. 

Is it possible for you to execute the target strip command on the host machine? If so, we can probably do better (a hook seems possible).

**Comment by jpellegrini** [comment] 2020-09-07 20:19
Yes, and the way i found to use strip when cross-compiling is in my latest pull requedt. Did you ser that?

PS: will be away for a couple days again

**Comment by egallesio** [comment] 2020-09-07 21:37
Just seen the PR. Sorry!!
I will look at it asap.

**Comment by egallesio** [comment] 2020-09-21 13:27
I have just changed the initialization of STRIP to 
```
STRIP         ?= strip
```
despite your comment on an empty STRIP because `automake` complains and says that the used form is not portable. Is it OK for you?

**Comment by jpellegrini** [comment] 2020-09-21 18:39
> Is it OK for you?

It seems to work! :)

**Comment by egallesio** [comment] 2020-10-22 13:10
Hi @jpellegrini,  I close this one to have a better vision of what issues needs some work.
Hope it is OK for you.

**Closed by egallesio** 2020-10-22 13:10 UTC
