### ISSUE TITLE
Garbage collection not running during tests?

### ISSUE THREAD

**Issue by jpellegrini** [egallesio/STklos#208] opened 2021-05-02 10:39 UTC
This program repeatedly allocates a large memory chunk:
```
(let ((v #f))
  (dotimes (i 1000000)
    (set! v (make-vector 100000))
    (display "."))
  (newline))
```

If I compile it with `stklos-compile` of if I load it on the REPL, it works just fine! Lots of dots are printed, and STklos does not seem to use much memory. Perfect!

Now... If I copy that file to the `tests` directory and add it as if it were one of the tests, in `do-test.stk`:
```
  (load "test-srfi.stk")
  (load "mem.stk")       ; <== here
  (load "test-json.stk")
```

and run `make test`, then STklos consumes several gigabytes during the tests.

With system `libgc` (8.0.4) it will just grow memory usage to several Gb; with the STklos provided `libgc`, which also seems to be 8.0.4, it also prints the following warning several times:

```
GC Warning: Repeated allocation of very large block (appr. size 802816):
	May lead to memory leak and poor performance
```

And crashes, showing the following error message:

```
Too many heap sections: Increase MAXHINCR or MAX_HEAP_SECTS
make[1]: *** [Makefile:476: test] Aborted
```

I have done this test because:

* I was working on SRFI-194 (Random Data Generators), and noticed that the tests exhaust all memory on my system (32Gb!);
* The finalizers for SRFi-25 do not run during the tests (issue #201 ), but they *sometimes* run when I use it from the REPL.

So, maybe gc is being disabled for some reason during tests? That would be really strange, and `grep gc tests/*stk` does not show anything. (?)

**Comment by egallesio** [comment] 2021-05-03 09:09
Hi @jpellegrini,

The GC is not blocked during tests. 
I think that the problem is resolved at least on x86_64.

>  For Linux, we used to add the _REENTRANT and GC_LINUX_THEADS compile  options (as required by GC documentation). However, it seems more harmful than useful now (at least on x86_64).                               
 >                                                                               
 >  Everything seem OK after having suppressing these options to compile  STklos (with and without provided GC). used 2 to 8 threads with  heavy allocations without abnormal memory consumption.    
>
> Need to be tested on other Linux architectures. 


I have tested with the following code 

```scheme
(define (foo n)
  (λ ()
    (let ((v #f))
      (dotimes (i 100000)
        (set! v (make-vector 100000))
        (if (zero? (modulo i 1000)) (printf "Thread #~a: ~a\n" n i))))))

(dotimes (i 8)
   (thread-start! (make-thread (foo i))))
```
on an X86_64 architecture and didn't notice any problem. 

I will also try to test it on an old Rasberry (I'm a bit worried to not do what is required in GC documentation).

**Comment by jpellegrini** [comment] 2021-05-03 09:46
> I'm a bit worried to not do what is required in GC documentation

Yes. Maybe we could ask the libgc people about this later?

**Comment by jpellegrini** [comment] 2021-05-03 09:47
> on an X86_64 architecture and didn't notice any problem.

That's great! I'll check if the issues I was having were fixed.

**Comment by jpellegrini** [comment] 2021-05-03 10:28
@egallesio here are a couple of things I noticed with this patch:

* SRFI-194 tests do not eat a lot of memory anymore!
* The shared array counter for SRFI-25 is in somewhat better situation: the finalizers are called, but I'm not sure we can force GC to happen, so although the counters are technically correct, it seems we can't test them
* Sometimes the tests for SRFI-41 enter an infinite loop (that did not happen before)

**Comment by jpellegrini** [comment] 2021-05-03 11:20
> * Sometimes the tests for SRFI-41 enter an infinite loop (that did not happen before)

I'm not sure about that. It seems to have happened a few times, but after recompiling and testing more than 20x, it did not happen again. It could have been because of some leftover stuff from previous compilations, maybe.

**Comment by jpellegrini** [comment] 2021-05-03 12:29
> For Linux, we used to add the _REENTRANT and GC_LINUX_THEADS compile options

I saw the docs... They seem to tell us to use `GC_THREADS` instead of `GC_LINUX_THREADS`, which is deprecated. I'm not sure if it makes a difference.

**Comment by egallesio** [comment] 2021-05-04 14:53
> SRFI-194 tests do not eat a lot of memory anymore!

Great.

> I saw the docs... They seem to tell us to use GC_THREADS instead of GC_LINUX_THREADS, which is deprecated. I'm not sure if it makes a difference.

I have tested with one or the other with and without _REENTRANT several times and I had **NO** problems when compiling STklos without any option. Consequently, I propose to keep it as is. 

@jpellegrini , tell me if it is OK for you.

BTW, I have tested also on a Raspberry (armv7l) and see no problem either when compiling STklos without option.

**Comment by jpellegrini** [comment] 2021-05-04 17:11
> @jpellegrini , tell me if it is OK for you.

I'm just not sure it works on all platforms. I was really unlucky recently:  I can' compile STklos on Android 11 (as I mentioned ni another issue), and I also can't compile the new version of OpenWRT for my router (something goes wrong when compiling the toolchain -- I'm working on it).
But I think it'll probably work.

**Comment by jpellegrini** [comment] 2021-05-04 17:19
> > SRFI-194 tests do not eat a lot of memory anymore!
> 
> Great.
 
Yes, but a very small part of the tests fail, and although they don't use much memory, they take a lot of time to finish. This seems to be related to SRFI-27.   I'll work on optimizing it (this one is worth being partially implemented in C). I've made some tests using the GMP random number generator instead of the SRFI-27 reference implementation in C, and it becomes twice as fast. But the GMP generator is not good for that, because the SRFI requires that the internal state have a printed representation, and the GMP does not have a function that allows us to see into the PRNG state.
Anyway, we talk about that more later.

**Comment by jpellegrini** [comment] 2021-05-05 18:42
I'm trying to see if anything breaks when compiling on other architectures. Will bring more information in the next hours/days.

**Comment by jpellegrini** [comment] 2021-05-06 02:39
Still couldn't get an Android device that is not Android 11.
But the changes do not seem to affect compiling and running on OpenWRT (on that big-endian MIPS machine)... It works fine.

**Comment by jpellegrini** [comment] 2021-05-06 14:12
Passes all tests on Android 11 too (see PR #199 )!

**Comment by jpellegrini** [comment] 2021-05-06 23:10
I adapted the STklos tests and ran them on a MIPS big-endian router running OpenWRT. No errors. :)
And the tests also pass on Android 11.
Maybe we can close this issue?

**Comment by egallesio** [comment] 2021-05-07 08:14
Great. 
Thanks, @jpellegrini for all your tests. 

I close this issue.

**Closed by egallesio** 2021-05-07 08:14 UTC
