### ISSUE TITLE
Building with `make -j$(nproc --ignore 1)` fails non-deterministically

### ISSUE THREAD

**Issue by amirouche** [egallesio/STklos#427] opened 2022-11-30 09:22 UTC

**Comment by jpellegrini** [comment] 2022-11-30 11:05
Hi @amirouche !
What error message exactly do you get?  I do see a failure sometimes when doing parallel builds. Can't remember exactly what the error was, but I'll copy and paste it here next time it happens.

**Comment by amirouche** [comment] 2022-11-30 11:21
> Can't remember exactly what the error was, but I'll copy and paste it here next time it happens.

I did not take the time to keep track of the errors. I will do so next time I have some CPU available.

**Comment by jpellegrini** [comment] 2022-11-30 12:03
Aha. Here it is:

```
gcc -g -O2  -g -O2 -rdynamic  -o stklos base64.o boolean.o boot.o box.o char.o cond.o cpointer.o dynload.o env.o error.o extend.o ffi.o fixnum.o fport.o gnu-getopt.o hash.o keyword.o lib.o list.o misc.o md5.o number.o object.o parameter.o path.o port.o print.o proc.o process.o promise.o read.o regexp.o signal.o sio.o socket.o sport.o stklos.o str.o struct.o symbol.o syntax.o system.o utf8.o uvector.o vector.o vm.o vport.o thread-common.o thread-pthreads.o mutex-common.o mutex-pthreads.o  -lgmp -lpcre  -lpcreposix -lffi  -lgc -lpthread -ldl  -lm -lpthread 
make[2]: Leaving directory '/home/jeronimo/pkg/scheme/STklos-github/src'
make[1]: Leaving directory '/home/jeronimo/pkg/scheme/STklos-github/src'
Making all in utils
make[1]: Entering directory '/home/jeronimo/pkg/scheme/STklos-github/utils'
./tmpcomp -o stklos-compile stklos-compile.stk
./tmpcomp -o stklos-genlex stklos-genlex.stk
./tmpcomp -o stklos-pp stklos-pp.stk
chmod a+x stklos-script
make[1]: Leaving directory '/home/jeronimo/pkg/scheme/STklos-github/utils'
Making all in lib
make[1]: Entering directory '/home/jeronimo/pkg/scheme/STklos-github/lib'
../src/stklos -q -l srfis.stk \
                 -f ../utils/update-srfi-list.stk \
                     -- --internal > srfis-data.scm
../utils/tmpcomp -o getopt.ostk getopt.stk
WARNING: "getopt" was not provided
**** Error while executing command ("../utils/update-srfi-list.stk" "--internal")

EXIT
make[1]: *** [Makefile:917: srfis-data.scm] Error 70
make[1]: *** Waiting for unfinished jobs....
make[2]: Entering directory '/home/jeronimo/pkg/scheme/STklos-github/src'
make  all-am
make[3]: Entering directory '/home/jeronimo/pkg/scheme/STklos-github/src'
make[3]: Leaving directory '/home/jeronimo/pkg/scheme/STklos-github/src'
make[2]: Leaving directory '/home/jeronimo/pkg/scheme/STklos-github/src'
make[1]: Leaving directory '/home/jeronimo/pkg/scheme/STklos-github/lib'
make: *** [Makefile:429: all-recursive] Error 1
```

**Comment by jpellegrini** [comment] 2022-11-30 12:05
But it doesn't happen in all machines. On a notebook that I use at work compilation always succeeds. The error happens on my home desktop only (not strange, since it has to do with concurrency).

**Comment by jpellegrini** [comment] 2022-11-30 12:15
```
../utils/tmpcomp -o getopt.ostk getopt.stk
WARNING: "getopt" was not provided
```

This warning is not issued when the build succeeds. Only when it fails.
But it doesn't fail compiling `getopt.stk`, it fails in 
```
**** Error while executing command ("../utils/update-srfi-list.stk" "--internal")
```

**Comment by jpellegrini** [comment] 2022-11-30 12:24
Hmmm. `update-srfi-list.stk` uses `parse-arguments.stk`, which is defined in `getopt.stk`.
Bu the `Makefile` dependencies do not reflect that.

**Comment by jpellegrini** [comment] 2022-11-30 12:32
@egallesio --
It seems that adding `getopt.ostk` as dependency to this rule:
```
srfis-data.scm: srfis.stk
	$(STKLOS_BINARY) -q -l srfis.stk \
        ...
```
in `lib/Makefile.am` fixes the problem. I'm not sure if this is the best way, as I'm not an expert in autotools (are dependencies handled somewhere else?)

**Comment by jpellegrini** [comment] 2022-11-30 12:39
See PR #429 (still not sure if it's the best way, but seems to work)

**Comment by amirouche** [comment] 2022-11-30 19:29
There is another one:

```
...
make[1]: Leaving directory '/home/amirouche/tmp/STklos/src'
Making all in utils
make[1]: Entering directory '/home/amirouche/tmp/STklos/utils'
./tmpcomp -o stklos-compile stklos-compile.stk
./tmpcomp -o stklos-genlex stklos-genlex.stk
./tmpcomp -o stklos-pp stklos-pp.stk
chmod a+x stklos-script
make[1]: Leaving directory '/home/amirouche/tmp/STklos/utils'
Making all in lib
make[1]: Entering directory '/home/amirouche/tmp/STklos/lib'
../utils/tmpcomp -o getopt.ostk getopt.stk
make[2]: Entering directory '/home/amirouche/tmp/STklos/src'
../src/stklos -q -l srfis.stk \
                 -f ../utils/update-srfi-list.stk \
                     -- --internal > srfis-data.scm
../utils/tmpcomp -o compfile.ostk compfile.stk
make  all-am
make[3]: Entering directory '/home/amirouche/tmp/STklos/src'
(cd ..; make SUPPORTED-SRFIS)
make[3]: Leaving directory '/home/amirouche/tmp/STklos/src'
make[2]: Leaving directory '/home/amirouche/tmp/STklos/src'
make[2]: Entering directory '/home/amirouche/tmp/STklos'
make[2]: 'SUPPORTED-SRFIS' is up to date.
make[2]: Leaving directory '/home/amirouche/tmp/STklos'
*** Boot 0
WARNING: "compfile" was not provided
**** Error while executing command ("bb.stk" "boot.img0" "instr0")

EXIT
make[1]: *** [Makefile:856: ../src/boot.img] Error 70
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/home/amirouche/tmp/STklos/lib'
make: *** [Makefile:429: all-recursive] Error 1
# 
```

**Comment by amirouche** [comment] 2022-11-30 19:33
I doing tests with your branch, and the following patch:

```
diff --git a/lib/Makefile.am b/lib/Makefile.am
index 44dd75e1..76479408 100644
--- a/lib/Makefile.am
+++ b/lib/Makefile.am
@@ -34,6 +34,7 @@ scheme_BOOT = assembler.stk \
           bonus.stk         \
           boot.stk          \
           callcc.stk        \
+          compfile.stk      \
           compiler.stk      \
           computils.stk     \
           date.stk          \
```

**Comment by jpellegrini** [comment] 2022-11-30 19:34
I suppose this last one can be fixed by changing `compfile.ostk` from the `all-recursive` rule to the `boot` rule:

from
```
all-recursive: boot generate-git-info compfile.ostk

boot:   ../src/boot.img
```
to:
```
all-recursive: boot generate-git-info 

boot:   ../src/boot.img compfile.ostk
```
I'm testing.

**Comment by jpellegrini** [comment] 2022-11-30 19:39
@amirouche I am testing with the solution I have suggested (changing the position of dependency `compfile.ostk`, but since I was not getting errors before, maybe I won't be sure if this fixes the problem. Perhaps your solution is better (adding `compfile.stk` to the `scheme_BOOT` variable). Tell us if it works!

**Comment by amirouche** [comment] 2022-11-30 21:57
With `make -j2` it worked a dozen of times. I need to do more test with `make -j9`

Really, what will be best is to infer the dependencies from the files using [topological sorting](https://srfi.schemers.org/srfi-234/), but I do not know how feasible it is, because dependencies may be implicit or hard to extract.

**Comment by amirouche** [comment] 2022-11-30 22:11
@jpellegrini I sent a pull request against your fork :+1:

**Comment by jpellegrini** [comment] 2022-12-01 00:19
> infer the dependencies from the files using [topological sorting](https://srfi.schemers.org/srfi-234/), but I do not know how feasible it is, because dependencies may be implicit or hard to extract.

Yes, topological sorting is, conceptually, the right thing to do, and I think Make does that. The hard part is to figure out the dependencies and declare them. A rule A may need to depend on rule B because B would write a file that A would need, and so on...

**Closed** 2023-02-02 08:58 UTC

**Comment by egallesio** [comment] 2023-02-02 09:13
Sorry for the long delay, but I was not able to reproduce it. 
Anyway, I have applied the path in PR #429. 
About the `compfile` dependency (if you remember, since it was a long time ago :wink:), it was no more necessary since
the function `compile-file` is now in the core image. 

Thanks a lot @amirouche and @jpellegrini on this issue.
